Repository GSG-G11/team-7-autocomplete-website, pull requests merged in 2022-02, with the labels that each got.

#2 create File Structre
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/index.html
  public/js/app.js
  public/js/dom.js
  public/js/fetch.js
  public/style.css
  src/countries.json
  src/router.js
  src/server.js
Labels: Done

#4 Configer folder public
  .eslintrc.json
  public/css/style.css
  public/index.html
  public/js/dom.js
  public/js/fetch.js
  public/style.css
Labels: Awaiting Review

#9 added server functions
  public/index.html
  public/js/dom.js
  public/js/fetch.js
  src/handler/fetch.js
  src/router.js
Labels: Approved

#10 style the website and error page
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  public/css/style.css
  public/index.html
  public/js/dom.js
  public/js/fetch.js
  public/style.css
  src/router.js
  src/server.js
Labels: Awaiting Review

#12 add fivicon
  public/index.html
Labels: Awaiting Review

#14 fixed bugs
  package-lock.json
  public/index.html
  public/js/dom.js
Labels: Awaiting Review

#15 fix bugs
  public/favicon.ico
  public/index.html
  src/handler/publicHandler.js
  src/router.js
Labels: Awaiting Review

#20 Fix bug in code and abstraction our codes
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  public/index.html
  public/js/app.js
  public/js/dom.js
  public/js/fetch.js
  public/style.css
  src/handler/fetch.js
  src/handler/publicHandler.js
  src/router.js
  src/server.js
Labels: Approved

#21 Update README.md
  README.md
Labels: Awaiting Review

#22 Update README
  README.md
Labels: Approved
